// Code generated by Thrift Compiler (0.14.2). DO NOT EDIT.

package simple

import(
	"bytes"
	"context"
	"fmt"
	"time"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal


func init() {
}

